package com.example.StoreFacePrintBynamoDb.entity;

import org.springframework.data.annotation.Transient;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;



@DynamoDBTable(tableName = "UserFacePrints")
public class UserEntity {

	@DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "userId")
    private String userId;

    @DynamoDBAttribute(attributeName = "FullName")
    private String fullName;

    @DynamoDBAttribute(attributeName = "WhatsappNumber")
    private String whatsappNumber;

   @DynamoDBAttribute(attributeName = "FacePrintData")
   private byte[] facePrintData;

    @Transient
    private boolean isNew;

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getFullName() {
		return fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getWhatsappNumber() {
		return whatsappNumber;
	}

	public void setWhatsappNumber(String whatsappNumber) {
		this.whatsappNumber = whatsappNumber;
	}

	public boolean isNew() {
		return isNew;
	}

	public void setNew(boolean isNew) {
		this.isNew = isNew;
	}

	public byte[] getFacePrintData() {
		return facePrintData;
	}

	public void setFacePrintData(byte[] facePrintData) {
		this.facePrintData = facePrintData;
	}




}
